analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    unused_element: warning

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    use_key_in_widget_constructors: false
    library_private_types_in_public_api: false
